# Generated by Django 4.2.1 on 2023-06-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToxicPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('toxic', models.FloatField()),
                ('severe_toxic', models.FloatField()),
                ('obscene', models.FloatField()),
                ('threat', models.FloatField()),
                ('insult', models.FloatField()),
                ('identity_hate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
